apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checker
  namespace: ymc
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: checker
            image: forana/ymc:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: config
            resources:
              requests:
                memory: "50Mi"
                cpu: "100m"
              limits:
                memory: "100Mi"
                cpu: "500m"
          restartPolicy: Never
      backoffLimit: 4
