name: Docker build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build image
        run: |
          docker buildx build \
            --tag forana/ymc:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
